org: carlosvini
app: salvistas
service: serverless-pdf-puppeteer
frameworkVersion: "3.28.1"

provider:
  name: aws
  versionFunctions: false
  runtime: nodejs14.x
  region: us-east-1
  stage: dev
  profile: salvistas

  apiGateway:
    binaryMediaTypes:
      - "application/pdf"
plugins:
  - serverless-webpack
  - serverless-offline
  # - serverless-domain-manager

custom:
  webpack:
    webpackConfig: webpack.config.js
    includeModules: true
    packager: "yarn"

  serverless-offline:
    location: .webpack/service

  # customDomain:
  #   domainName: labs.mianio.com
  #   basePath: demo
  #   stage: ${self:provider.stage}
  #   createRoute53Record: true

functions:
  give-me-the-pdf:
    handler: functions/pdf.generate
    events:
      - http:
          path: puppeteer/pdf
          method: get
          cors: true
